[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tutor"
version = "0.0.1"
requires-python = ">= 3.12"
dependencies = [
  "fastapi[standard]",
  "openai",
  "requests==2.32.3",
  "supabase==2.13.0"
]